version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379

  node1:
    build: ./app
    ports: 
      - 8080
    links:
      - redis
    environment:
      - CONTAINER=node1

  node2:
    build: ./app
    ports: 
      - 8080
    links:
      - redis
    environment:
      - CONTAINER=node2

  node3:
    build: ./app
    ports: 
      - 8080
    links:
      - redis

    environment:
      - CONTAINER=node3

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - node1
      - node2
      - node3